# Generated by Django 5.0.2 on 2024-02-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=60)),
                ('pin_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.user')),
            ],
        ),
    ]
