# Generated by Django 5.0.7 on 2024-08-07 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_desc', models.CharField(max_length=255)),
                ('discount_percent', models.FloatField(max_length=3)),
                ('discount_active', models.BooleanField()),
                ('discount_created_at', models.DateField(auto_now_add=True, null=True)),
                ('discount_modified_at', models.DateField(blank=True, null=True)),
                ('discount_deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.CharField(max_length=255)),
                ('category_image', models.ImageField(upload_to='images/')),
                ('category_created_at', models.DateField(auto_now_add=True, null=True)),
                ('category_modified_at', models.DateField(blank=True, null=True)),
                ('category_deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory_created_at', models.DateField(auto_now_add=True, null=True)),
                ('inventory_modified_at', models.DateField(blank=True, null=True)),
                ('inventory_deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.custom_user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('order_details_created_at', models.DateField(auto_now_add=True, null=True)),
                ('order_details_modified_at', models.DateField(blank=True, null=True)),
                ('order_details_deleted_at', models.DateField(blank=True, null=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paymen_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.payment_details')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=255)),
                ('SKU', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jungleekartapp.brand')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.discount')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.product_category')),
                ('inventory_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.product_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_created_at', models.DateField(auto_now_add=True, null=True)),
                ('order_modified_at', models.DateField(blank=True, null=True)),
                ('order_deleted_at', models.DateField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.order_details')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.cart_details')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jungleekartapp.product')),
            ],
        ),
    ]
